### ISSUE TITLE
[Calendar] Декомпозиция

### ISSUE THREAD

**Issue by pavel-b-novikov** [mertevalery/nsudotnet#1]
Боже, зачем вам 16 методов?

Сейчас мы сделаем простое упражнение, которое добавит больше понимания в то, как делать процедурную декомпозицию.

Устраните все методы, которые вызываются ОДИН раз

**Comment by mertevalery** [comment]
Дикая тупость. Исправил.

**Comment by pavel-b-novikov** [comment]
И всегда проверяйте свой код на это простое правило. Если метод вызывается один раз - то он не нужен. Исключение - методы в других архитектурных слоях (сборках) с потенциальном композиции и многкратного вызова
