### ISSUE TITLE
[LinesCounter] Трим строки

### ISSUE THREAD

**Issue by pavel-b-novikov** [mertevalery/nsudotnet#4]
Объясните необходимость вызова .Trim

**Comment by mertevalery** [comment]
Trim() удаляет символы разделители. Это нужно для того, чтобы не засчитывались подобные строки:
[пробел]//комментарий
[пробел]/*комментарий 
и т.д.

**Comment by pavel-b-novikov** [comment]
А без Trim-а в принципе эту задачу решить можно? Равно как и без конструирования лишних строк вообще, за один проход по файлу?

**Comment by mertevalery** [comment]
Через индексы, но это я уже подсмотрел. Переписывать?

**Comment by pavel-b-novikov** [comment]
Да ладно, живите пока
