### ISSUE TITLE
[LinesCounter] GetFiles

### ISSUE THREAD

**Issue by pavel-b-novikov** [mertevalery/nsudotnet#5]
В чем разница между Directory.GetFiles и Directory.EnumerateFiles?

**Comment by mertevalery** [comment]
GetFiles возвращает имена файлов System.String[]
EnumerateFiles возвращает перечисляемую коллекцию имен файлов IEnumerable<String>

**Comment by pavel-b-novikov** [comment]
Спасибо капитан очевидность. А если я сделаю .GetFiles().AsEnumerable() - это будет то же самое?

**Comment by mertevalery** [comment]
Нашел ответ 
The EnumerateFiles and GetFiles methods differ as follows: When you use EnumerateFiles, you can start enumerating the collection of names before the whole collection is returned; when you use GetFiles, you must wait for the whole array of names to be returned before you can access the array.

По-русски говоря, с большими директориями, где много файлов и папок, Enumerate более эффективен.

**Comment by pavel-b-novikov** [comment]
Алилуйя
